// FETCH TRENDING - START

export const GET_FEATURED_BEGIN = "GET_FEATURED_BEGIN";
export const GET_FEATURED_SUCCESS = "GET_FEATURED_SUCCESS";
export const GET_FEATURED_ERROR = "GET_FEATURED_ERROR";

// FETCH SEARCH MOVIES
export const GET_RECORDS_BEGIN = "GET_RECORDS_BEGIN";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export const GET_RECORDS_ERROR = "GET_RECORDS_ERROR";

// FETCH SINGLE MOVIE

export const GET_SINGLE_RECORD_BEGIN = "GET_SINGLE_RECORD_BEGIN";
export const GET_SINGLE_RECORD_SUCCESS = "GET_SINGLE_RECORD_SUCCESS";
export const GET_SINGLE_RECORD_ERROR = "GET_SINGLE_RECORD_ERROR";

// FILTER MOVIES
export const FILTER_MOVIES = "FILTER_MOVIES";
export const ADD_FAVORITE = "ADD_FAVORITE";

// FAVORITE MOVIES
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const PERSONAL_SCORE_ADD = "PERSONAL_SCORE_ADD";
export const PERSONAL_SCORE_MODIFY = "PERSONAL_SCORE_MODIFY";

// HOME LOADING
export const HOME_LOADING = "HOME_LOADING";

// GENRES FETCH
export const GET_GENRES_ERROR = "HOME_LOADING";
export const GET_GENRES = "HOME_LOADING";

// EXTRA MOVIE INFO

export const GET_EXTRA_RECORD_INFO_BEGIN = "GET_EXTRA_RECORD_INFO_BEGIN";
export const GET_EXTRA_RECORD_INFO_ERROR = "GET_EXTRA_RECORD_INFO_ERROR";
export const GET_EXTRA_RECORD_INFO_SUCCESS = "GET_EXTRA_RECORD_INFO_SUCCESS";

// FAVORITE

export const GET_FAVORITE_MOVIES = "GET_FAVORITE_MOVIES";
export const GET_FAVORITE_SERIES = "GET_FAVORITE_SERIES";
export const GET_FAVORITES = "GET_FAVORITES";
